version: "3.8"
services:
  postgres:
    image: 'postgres:15.2-alpine'
    container_name: postgres
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      TZ: UTC
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "log_statement=all"]

  pgAdmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
